### PR TITLE
Fix: When changing username in Linux the fullname still return

### PR DESCRIPTION
**Pull request by FoxieFlakey**
original username

Found this when i change username and run yo (it print 'Allo {the old username}' instead new one)
Add 'LOGNAME' and 'USER' to the 'enviromentVariables' just that i did i cant really code in javascript and i tested it on my linux

### CODE REVIEW

**Comment by NickWilde263** [comment]
replace old `enviromentVariables` with
```
const environmentVariables = [
	'GIT_AUTHOR_NAME',
	'GIT_COMMITTER_NAME',
	'HGUSER', // Mercurial
	'C9_USER', // Cloud9
	'LOGNAME',
	'USER'
];
```
i tried but check fail and im only touch the enviromentVariables

**Comment by NickWilde263** [comment]
it work on my linux but why checks failing

**Comment by sindresorhus** [comment]
Can you link to a source that describes these added environment variables?

**Comment by NickWilde263** [comment]
At index.js Line 8 the `const enviromentVariables`

**Comment by NickWilde263** [comment]
replace it with
```
const environmentVariables = [
	'GIT_AUTHOR_NAME',
	'GIT_COMMITTER_NAME',
	'HGUSER', // Mercurial
	'C9_USER', // Cloud9
	'LOGNAME',
	'USER'
];
```
LOGNAME and USER enviroment variable is Linux specific (add it to reflect username changing in linux)

**Comment by NickWilde263** [comment]
because last time i change the username the `fullname` give the old username even after relogging

**Comment by NickWilde263** [comment]
```
  ✔ should get fullname from env var
  ✔ respects changed env vars
  ✖ should get value from init-author-name 
  ✖ should get value from passwdUser for darwin platform 
  ✖ should get value from osascript for darwin platform if passwdUser returns empty username 
  ✖ should get value from osascript for darwin platform if passwdUser rejects 
  ✖ should get value from git global user for win32 platform 
  ✖ should get value from wmic for win32 platform if git global returns empty username 
  ✖ should get value from wmic for win32 platform if git global rejects 
  ✖ should get value from passwdUser for other platform and both other checks fail 
  ✖ should get value from getent for other platform and both other checks fail 
  ✖ should get value from git for other platform and both other checks fail 
  ✖ should get value from passwdUser for other platform and both other checks return empty string 
  ✖ should get value from getent for other platform and both other checks return empty string 
  ✖ should get value from git for other platform and both other checks return empty string 
```

why i just add more enviroment variable to search and i failed most of the test

**Comment by sindresorhus** [comment]
`environmentVariables` is expected to contain the full name, not the username.

**Comment by NickWilde263** [comment]
> `environmentVariables` is expected to contain the full name, not the username.

ok

**Pull request closed without merging**
